config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  mount Sidekiq::Web => "/sidekiq"

  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  root "posts#index"

  resources :posts do
    resources :comments
  end

  namespace :user do
    resource :dashboard, only: [:show]
    resource :passwords, only: [:update]
  end

  namespace :paypal do
    resources :orders, only: [:create] do
      resource :captures, only: [:create]
    end
  end

  resources :chapters, only: [:index]
  resources :contact, only: [:index, :create]
  resources :spirituality_for_devs, only: [:index]
end

app/views/shared/_breadcrumbs.html.haml
.font-small.margin-bottom-10
  = breadcrumbs.render(format: :inline, separator: "/")

app/views/shared/_navbar.html.haml
%nav#mainNav.navbar.navbar-expand-xl.navbar-light.fixed-top
  .container
    = link_to "Ramminti", root_path, class: "navbar-brand"
    %button.navbar-toggler.navbar-toggler-right{"aria-controls" => "navbarResponsive", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarResponsive", "data-bs-toggle" => "collapse", type: "button"}
      Menu
      %i.fas.fa-bars
    #navbarResponsive.collapse.navbar-collapse
      %ul.navbar-nav.ml-auto
        %hr/
        - if current_user.present?
          %li.nav-item
            = link_to current_user.first_name, user_dashboard_path, class: "nav-link"
        %li.nav-item
          = link_to "Spirituality for Devs!", spirituality_for_devs_path, class: "nav-link"
        - if params[:action] == "show" && (@next_post || @prev_post)
          %hr/
          %li.nav-item
            = link_to "prev: #{@next_post.title}", post_path(@next_post.friendly_id), class: "nav-link" if @next_post
            = link_to "next: #{@prev_post.title}", post_path(@prev_post.friendly_id), class: "nav-link" if @prev_post
          %hr/
        %li.nav-item
          - if current_user.present?
            = link_to "Salir", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link"
          - else
            = link_to "Iniciar", new_user_session_path, class: "nav-link"
        %hr/
        %div.d-block.d-xl-none
          %li.nav-item.me-4.me-xl-0.gap-4.d-flex.flex-column
            %button.btn.btn-toggle.d-inline-flex.align-items-center.rounded.border-0.collapsed{"aria-expanded" => "false", "data-bs-target" => "#account-collapse", "data-bs-toggle" => "collapse", style: "font-size: 12px;"}
              = "-> Estantes"
            #account-collapse.collapse{:style => ""}
              %ul.btn-toggle-nav.d-flex.flex-column.align-items-start
                - @shelves.each do |shelf|
                  %li.d-flex.flex-column.btn.btn-toggle.d-inline-flex.rounded.border-0.collapsed{style: "font-size: 12px;"}
                    = link_to shelf.name.titleize, "#{posts_path(tag: shelf.slug)}", class: "nav-link"

app/views/shared/_side_navbar.html.haml
%div.d-none.d-xl-block
  %nav.navbar.p-0
    %ul.navbar-nav.flex-row.flex-xl-column.flex-wrap.gap-2
      - @shelves.each_with_index do |shelf, shelf_index|
        %li.d-flex.nav-item.me-4.me-xl-0.gap-4{style: "flex-direction: row; align-items: start;"}
          =#- if shelf.boxes.any?
          = link_to "#{posts_path(tag: shelf.slug)}", class: "nav-link" do
            %p.m-0= "#{shelf.name.titleize}:"
          .d-flex{style: "flex-direction: column;" }
            = link_to "#{posts_path(tag: shelf.slug)}", class: "nav-link" do
              %span= "Total: #{shelf.posts_non_boxes.count}"
            - if shelf.slug != 'camino-zero'
              - shelf.boxes.each_with_index do |box, index_box|
                = link_to "#{posts_path(tag: box.slug)}", class: "nav-link" do
                  = box.title.titleize
                  = "(#{shelf.posts_by_parent_box(box.id).count})"
                -if index_box + 1 != shelf.boxes.size
                  %hr.m-0
              - shelf.posts_non_boxes_non_parent.each_with_index do |box, index_box|
                = link_to "#{posts_path(tag: box.slug)}", class: "nav-link" do
                  = box.title.titleize
                -if index_box + 1 != shelf.boxes.size
                  %hr.m-0/
        -if shelf_index + 1 !=  @shelves.size
          %hr.m-0/