config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  mount Sidekiq::Web => "/sidekiq"

  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  root "posts#index"

  resources :posts do
    resources :comments
  end

  namespace :user do
    resource :dashboard, only: [:show]
    resource :passwords, only: [:update]
  end

  namespace :paypal do
    resources :orders, only: [:create] do
      resource :captures, only: [:create]
    end
  end

  resources :chapters, only: [:index]
  resources :contact, only: [:index, :create]
  resources :spirituality_for_devs, only: [:index]
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy

  def paid_orders
    orders.where(status: Order.statuses[:paypal_executed]).or(Order.where(status: Order.statuses[:paid]))
  end

  def update_password_with_password(params, *options)
    current_password = params.delete(:current_password)

    result = if valid_password?(current_password)
               update(params, *options)
             else
               self.assign_attributes(params, *options)
               self.valid?
               self.errors.add(:current_password, current_password.blank? ? :blank : :invalid)
               false
             end

    clean_up_passwords
    result
  end
end

app/controllers/user/dashboards_controller.rb
class User::DashboardsController < ApplicationController
  def show
    @private_chapters = Post.where(is_private: true).left_joins(:orders).where(orders: {user_id: nil})
  end
end

app/controllers/user/passwords_controller.rb
class User::PasswordsController < ApplicationController
  before_action :authenticate_user!

  def edit
    @user = current_user
  end

  def update
    @user = User.find(current_user.id)
    if @user.update_password_with_password(user_params)
      sign_in @user, bypass: true
      redirect_to user_dashboard_path, flash: { success: "Successfully updated password" }
    else
      redirect_to user_dashboard_path, flash: { alert: @user.errors.full_messages.to_sentence }
    end
  end

  private

  def user_params
    params.permit(:current_password, :password, :password_confirmation)
  end

end

app/views/user/dashboards/_account.html.haml
%h3= "Tu cuenta"
.col-10
  %p= "email: #{current_user.email}"
  %p{style: "font-style: italic"}= "nota: mira tu email si no sabes tu contraseña actual, o haz click en 'salir' -> 'olvide la contraseña'"
  %h5= "Actualizar contraseña:"
  - if flash.any?
    - flash.each do |type, msg|
      - alert = type == "alert" ? 'danger' : 'success'
      %div.col-12.col-sm-10.offset-sm-1.col-md-8.offset-md-2.alert{class: "alert-#{alert}", role: "alert" }
        = msg

  = form_with url: user_passwords_path, method: :put  do |form|
    .control-group
      .form-group.floating-label-form-group.controls
        %label Contraseña actual
        = form.password_field :current_password, class: "form-control", type: "password", id: "current_password", placeholder: "Contraseña actual", data: {"validation-required-message": "Ingrese contraseña actual."}
        %p.help-block.text-danger

    .control-group
      .form-group.floating-label-form-group.controls
        %label Nueva contraseña
        = form.password_field :password, class: "form-control", placeholder: "Nueva contraseña", data: {"validation-required-message": "Ingrese nueva contraseña."}
        %p.help-block.text-danger

    .control-group
      .form-group.floating-label-form-group.controls
        %label Confirma nueva contraseña
        = form.password_field :password_confirmation, class: "form-control", placeholder: "Confirma nueva contraseña", rows: 5, data: {"validation-required-message": "Confirme la nueva contraseña."}
        %p.help-block.text-danger

    %br/
    #success
    = form.submit "Guardar", class: "btn btn-primary"
    %br/
    = link_to "Olvidaste tu contraseña?", new_password_path(current_user), class: "nav-link"

app/views/user/dashboards/_orders_empty_state.html.haml
.col-10
  %p.alert.alert-warning= "Upps... Parece que aún no tienes capítulos desbloqueados, echa un vistazo ;)"
  %hr.my-5/

app/views/user/dashboards/_paid_orders.html.haml
.col-12.offset-2
  %h5= "Lista de capítulos privados a los que tienes accesso:"
  .border.border-opacity-10.rounded-3.p-4.mt-3
    %table.table.table-hover.mb-0.js-paid-orders-table
      %thead
        %tr
          %th.border-top-0{:scope => "col"} #
          %th.border-top-0{:scope => "col"} Título
          %th.border-top-0{:scope => "col"} Donation (usd)
          %th.border-top-0{:scope => "col"} Orden ID
          %th.border-top-0{:scope => "col"} Ver
      %tbody
        - current_user.paid_orders.each_with_index do |order, index|
          %tr{id: "#paid_order_#{index}"}
            %th{:scope => "row"}= index
            %td.border-bottom-0= order.post.title
            %td.border-bottom-0= order.price
            %td.border-bottom-0= order.charge_id
            %td.border-bottom-0= link_to "Ver", post_path(order.post.friendly_id), class: "js-link-to-post"

  %hr.my-5/

app/views/user/dashboards/_private_chapters.html.haml
%h5= "Lista de capítulos privados:"
.border.border-opacity-10.rounded-3.p-4.mt-3
  %table.table.table-hover.mb-0.js-private-chapters-table{style: "cursor: pointer;"}
    %thead
      %tr
        %th.border-top-0{:scope => "col"} Título
        %th.border-top-0{:scope => "col"} Donar
    %tbody
      - @private_chapters.each do |private_chapter|
        %tr
          %td.border-bottom-0= private_chapter.title
          %td.border-bottom-0= link_to "Donar", post_path(private_chapter.friendly_id), class: "js-link-to-post"

%hr.my-5/

app/views/user/dashboards/show.html.haml
.d-flex.flex-column.align-items-center.my-3
  - if current_user.paid_orders.any?
    = render partial: "user/dashboards/paid_orders"
  - else
    = render partial: "user/dashboards/orders_empty_state"

  = render partial: "user/dashboards/private_chapters", locals: {private_chapters: @private_chapters}

  = render partial: "user/dashboards/account"
  :javascript
    (function(){
      $( document ).ready(function() {
        $( ".js-private-chapters-table tbody" ).on( "click", "tr", function() {
          const postLink = $(this).find("a.js-link-to-post").attr('href');
          window.location.pathname = postLink;
        });
      })
    })();