config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  mount Sidekiq::Web => "/sidekiq"

  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  root "posts#index"

  resources :posts do
    resources :comments
  end

  namespace :user do
    resource :dashboard, only: [:show]
    resource :passwords, only: [:update]
  end

  namespace :paypal do
    resources :orders, only: [:create] do
      resource :captures, only: [:create]
    end
  end

  resources :chapters, only: [:index]
  resources :contact, only: [:index, :create]
  resources :spirituality_for_devs, only: [:index]
end

app/models/post.rb
class Post < ApplicationRecord
  monetize :price_cents

  CAMINO_ZERO = 'camino_0'
  CUENTOS = 'cuentos'

  extend FriendlyId
  friendly_id :title, use: :slugged
  attr_accessor :remove_main_image
  acts_as_taggable_on :tags

  belongs_to :parent_box, optional: true, class_name: "Post", foreign_key: :parent_box_id
  belongs_to :shelf

  has_one_attached :main_image
  has_many_attached :images
  has_many :comments
  has_many :orders

  scope :published, lambda { where(published: true, is_box: false) }
  scope :unpublished, lambda { where(published: false, is_box: false) }

  validates :title, presence: true
  validate :is_box_with_no_parent

  def self.camino_0_count
    Post.published.tagged_with(CAMINO_ZERO).count
  end

  def self.cuentos_count
    Post.published.tagged_with(CUENTOS).count
  end

  def shelf_name
    self.shelf.name
  end

  def parent_box_name
    self.parent_box&.title
  end

  def price_with_dolar_sign
    humanized_money_with_symbol(self.price)
  end

  def title_to_show_on_main_banner
    PageTitleGenerator.new(
      instace: self,
      generator: Posts::PageTitleGenerator
    ).show_on_main_banner
  end

  def image_to_show_on_main_banner
    PageImageGenerator.new(
      instace: self,
      generator: Posts::PageImageGenerator
    ).show_on_main_banner
  end

  def donation_value_price_cent
    return 100
  end

  private

  def is_box_with_no_parent
    self.errors.add(:base, "Only non-boxes can have parent.") if self.is_box? && self.parent_box_id.present?
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @current_boxes = Shelf.where(slug: params[:tag])

    @current_boxes = Post.where(is_box: true) unless @current_boxes.present?
    @current_box   = @current_boxes.tagged_with(params[:tag]).first
    @current_box   = Post.tagged_with(params[:tag]).first unless @current_box.present?

    @active_posts = Posts::ByTags.new(tag: params[:tag], scope: @active_posts).execute if params[:tag].present?
    @active_posts = @active_posts.paginate(page: params[:page]).order('created_at DESC')
  end

  def show
    active_record_posts = params[:show_draft].present? ? Post.unpublished : Post.published
    active_record_posts = active_record_posts.order('created_at DESC')
    @post = active_record_posts.friendly.find(params[:id])
    @current_box = @post #This is to setup instace variable used on the application_helper
    posts = active_record_posts.map.with_index{ |post, index| { index: index, post: post } }

    current_index_post = posts.select { |post| post[:post].id == @post.id }.first[:index]
    @next_post = current_index_post + 1 != posts.size  ? posts[current_index_post + 1][:post] : nil
    @prev_post = current_index_post > 0                ? posts[current_index_post - 1][:post] : nil

    @comments = Comment.where(post_id: @post.id).limit(20).order('created_at DESC')
    breadcrumbs.add "All Chapters", root_path
    breadcrumbs.add @post.title, post_path(@post)
  end

end

app/views/posts/_comment_list.html.haml
%article
  .container
    .row
      .div
        %hr
      %h5 Comments:
      .col-lg-8.col-md-10.mx-auto
        - if comments.any?
          - comments.each do |comment|
            .card.mb-4
              .card-body
                %p= comment.content
                .d-flex.justify-content-between
                  .d-flex.flex-row.align-items-center
                    %p.small.mb-0.ms-2= comment.name.split("@")[0]

app/views/posts/_new_comment_form.html.haml
.container
  .row
    .div
      %hr
    %h5#sayHi Say hi:
    .col-lg-8.col-md-10.mx-auto
      - post_params = {post_id: post_id}
      - post_params = params[:show_draft].present? ? post_params.merge!({show_draft: params[:show_draft]}) : post_params
      = form_with url: post_comments_path(post_params), html: {id: 'contactForm'} do |form|
        - flash.each do |type, msg|
          - alert = type == "alert" ? 'danger' : 'success'
          %div.col-12.col-sm-10.offset-sm-1.col-md-8.offset-md-2.alert{class: "alert-#{alert}",role: "alert" }
            = msg
        .control-group
          .form-group.floating-label-form-group.controls
            %label E-mail:
            = form.text_field :name, class: "form-control", placeholder: "name@example.com", value: params[:name]
        .control-group
          .form-group.floating-label-form-group.controls
            %label Comment:
            = form.text_area :content, class: "form-control", placeholder: "Comment out...", rows: 3, value: params[:content]
        %br/
        .control-group
          = form.submit "Send", class: "btn btn-primary", id: "sendMessageButton"
        %br/

app/views/posts/_next_prev_buttons.html.haml
.container
  .row
    .paypay-checkout{style: "width: 28%"}
    .next-prev-wrapper
      = link_to "prev: #{next_post.title}", post_path(next_post.friendly_id), class: "btn btn-secondary downset-1" if next_post
      = link_to "next: #{prev_post.title}", post_path(prev_post.friendly_id), class: "btn btn-secondary" if prev_post

app/views/posts/_post_content.html.haml
.d-flex.flex-column.col-12.col-xl-9.mx-auto.px-xl-0.px-3{:style=>"max-width: 800px; overflow-y: hidden"}
  %article.my-70
    = render partial: "shared/breadcrumbs"
    %h1= post.title
    %h5.mb-4
      - post.tag_list.each do |tag|
        - link_with_params_for_tag = params[:show_draft].present? ? posts_path(show_draft: true, tag: tag) : posts_path(tag: tag)
        = link_to link_with_params_for_tag do
          %span.badge.badge-pill.badge-brown=tag
    = post.content.html_safe

app/views/posts/_private_state.html.haml
- if current_user.present? && current_user.paid_orders.map(&:post_id).include?(post.id)
  .col-12.col-xl-3.d-flex.flex-column.justify-content-center.align-items-center.mx-auto.mx-xl-0.position-sticky{:style=>"top: 93px; z-index: 100;"}
    %h5.text-center Este proyecto es un esfuerzo individual; puedes ayudar donando.
    .d-flex.align-items-center.flex-column
      = image_tag(asset_url("flower_lotus.png"), class: "blankslate-top-img mb-2", style: "width: 240px;")
      %p= "Gracias por la donacion!"
- else
  .col-12.col-xl-3.d-flex.flex-column.justify-content-center.align-items-center.mx-auto.mx-xl-0.position-sticky{:style=>"top: 93px; z-index: 100;"}
    %h5.text-center Este proyecto es un esfuerzo individual; puedes ayudar donando.
    .d-flex.align-items-center.flex-column
      = image_tag(asset_url("flower_lotus.png"), class: "blankslate-top-img mb-2", style: "width: 240px;")
      %input#donationValue.form-control.paypal-container-width{:name => "donationValue", :type => "number", min: 1.0, value: 1.0, step: ".1", :style=>"margin-bottom: 5px;"}
    .paypal-conteiner.paypal-container-width

app/views/posts/index.html.haml
- content_for :title, flush: true do
  = @current_box&.title_to_show_on_main_banner

.d-flex.flex-column.col-12.col-xl-9.ms-auto.ms-xl-4.me-auto.px-3.px-lg-5.align-self-stretch{:style=>"max-width: 1000px; overflow-y: hidden"}
  - @active_posts.each do |post|
    .post-preview
      - link_with_params = params[:show_draft].present? ? post_path(post.friendly_id, show_draft: true) : post_path(post.friendly_id)
      = link_to link_with_params do
        %h3.mt-0.post-title= post.title
        %h4.post-subtitle= post.summary
      %div.next-prev-wrapper.d-flex{style: "align-items: flex-end;"}
        .mb-0.post-meta
          = link_to "Seguir Leyendo", link_with_params, class: "btn btn-secondary", html: {style: "width: 230px;"}
        .mb-0.post-meta
          - post.tags.each do |tag|
            - link_with_params_for_tag = params[:show_draft].present? ? posts_path(show_draft: true, tag: tag.name) : posts_path(tag: tag.name)
            = link_to link_with_params_for_tag do
              %span.badge.badge-pill.badge-brown=tag.name
        .mb-0.post-meta
          = post.created_at.strftime("%B %d, %Y")

    %hr/

  .col-lg-8.col-md-10.mx-auto.d-flex.d-xl-block.align-items-center.justify-content-center
    .digg_pagination
      = will_paginate @active_posts

app/views/posts/show.html.haml
- content_for :title, flush: true do
  = @current_box&.title_to_show_on_main_banner

- paypal_order = nil
- if current_user.present?
  - paypal_order = current_user.orders.where(post_id: @post.id, status: Order.statuses[:paypal_executed]).first

= render partial: "posts/post_content", locals: { post: @post }
=# render partial: "posts/private_state", locals: { post: @post }
= content_for :comments_on_single_post do
  = render partial: "posts/next_prev_buttons", locals: { next_post: @next_post, prev_post: @prev_post }
  = render partial: "posts/new_comment_form", locals: { post_id: @post.id }
  = render partial: "posts/comment_list", locals: { comments: @comments }

= content_for :paypay_buttons do
  %script{:src => "#{ENV['PAYPAL_BASE_URL']}" + "/sdk/js?client-id=" + "#{ENV['PAYPAL_CLIENT_ID']}"}
  :javascript
    paypal.Buttons({
      env: "#{ENV['PAYPAL_ENV']}",
      style: {
        layout: "vertical",
        borderRadius: 10,
        color: "blue",
        shape: "rect",
      },
      async createOrder() {
        const post_sku = '#{@post.slug}'
        const post_id = #{@post.id}
        const donation_value = $("#donationValue").val()
        const response = await fetch("/paypal/orders", {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
            },
            body: JSON.stringify({
              post_id: post_id,
              cart: [{
                  sku: post_sku,
                  quantity: 1,
                  donation_value: donation_value
              }]
            })
        });
        const order = await response.json();
        return order.id;
      },
      async onApprove(data) {
        const post_id = #{@post.id}
        const response = await fetch(`/paypal/orders/${data.orderID}/captures`, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            post_id: post_id,
            order_id: data.orderID
          })
        })

        const details = await response.json();
        window.location.reload();
      }
    }).render('.paypal-conteiner');